# Generated by Django 5.0.2 on 2024-03-26 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_acessorios"),
    ]

    operations = [
        migrations.RenameField(
            model_name="acessorios",
            old_name="acessorios",
            new_name="descricao",
        ),
    ]
